import {AuthorizationController} from "../functions/controller/authorization.controller.mjs";
import {SecretsUtil} from "../functions/utils/secrets.util.mjs";

describe('Authorization Integration Test', function () {
    const host = 'https://utsserver-faas.bfast.fahamutech.com';
    it('should return signed jwt', function () {
        const jwt = new AuthorizationController().getToken(SecretsUtil.keyPair, host);
        // console.log(jwt);
    });
    it('should generate jwk', function () {
        const jwkFull = new AuthorizationController().getJwk(SecretsUtil.keyPair);
        const jwkPrivate = new AuthorizationController().getJwk(SecretsUtil.publicKey);
        // console.log(jwk);
    });
    it('should verify token generated by private key', function () {
        const token = new AuthorizationController().getToken(SecretsUtil.keyPair, host);
        const rs = new AuthorizationController().verifyToken(token, SecretsUtil.publicKey);
        console.log(rs);
    });
});
